### get all comments
GET http://localhost:3000/comments

### get all comments with postId
GET http://localhost:3000/comments?postId=1

### get all comments with postId and includes post
GET http://localhost:3000/comments?postId=1&includes=post