### get all posts
GET http://localhost:3000/posts
###
### get post by postId
GET http://localhost:3000/posts/-1

###
### create post
POST http://localhost:3000/posts  HTTP/1.1
content-type: application/json

{
    "userId": 1,
    "title": "title 1",
    "body": "body is ma f*** body"
}
###
### patch data
PATCH  http://localhost:3000/posts/1  HTTP/1.1
content-type: application/json

{
    "title": "title 1",
    "body": "body is ma f*** body xoxo"
}

### delete data
DELETE   https://jsonplaceholder.typicode.com/posts/1 HTTP/1.1
