version: '3.8'
services:
  postges_db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: clone_jsonplaceholder
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  clone_jsonplaceholder_app_prod:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
    env_file:
      - ../.env.local
    ports:
      - '3000:3000'
    depends_on:
      - postges_db

volumes:
  postgres-data:
